# Numpy problems

### High School Reunion Problem
With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.

Given these daily weights, build an array with your average weight per weekend1.

In [1]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [2]:
# Problem defintion A weekend includes Saturday and Sunday (but not Friday)

array([184. , 182.6, 181.2, 179.8, 178.4])

In [3]:
# Approaching using slicing and arthimetic operations

weekend_wts = (dailywts[5: : 7] + dailywts[6: : 7])/2
print(weekend_wts)

[183.9 182.5 181.1 179.7 178.3]


### Gold Miner Problem
After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner  . You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

Notes:
gold states how much gold is under each location in the 7x7 grid of land

locs states the coordinates of the five locations where you dig

In [4]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [5]:
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [7]:
gold[0,4]

2

In [8]:
locs[ :, 0]

array([0, 2, 2, 5, 6])

In [9]:
locs[ :, 1]

array([4, 2, 3, 1, 3])

In [10]:
gold[ locs[ :, 0] , locs[ :, 1] ].sum()

20

### Chic-fil-A Problem
You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A 🐔.

* You buy three billboards evenly spaced starting from mile marker 17 and ending on mile marker 28.
* You buy another three billboards starting on mile marker 32 and ending on mile marker 36.
* In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A.

Determine how far each B ad is from your restaurant which is located at mile marker 30.

In [12]:
# ads / restaurant*:   A     B     C   *   C  B  A
# billboards:        --|-----|-----|---|---|--|--|--
# mile markers:       17          28  30  32    36

#### There are two ways to solve this problem through three different operations for evenly spaced lists:
* Use np.linspace when you know the number of points you need. (Straight way method but requires learning)
* Use np.arange when you know the interval (step size) but not the number of points (Usual and most used operations but requires calculation of step size)
* np.geomspace(start, stop, num) generates numbers that are evenly spaced on a logarithmic scale.

We’re placing billboards linearly (equal distances), so np.geomspace isn’t ideal since it creates exponential spacing. However, it's worth knowing when you're working with growth rates or percentages.

In [33]:
# Using np.arange 
first_3 = np.arange(17, 28.1 , (28-17)/2)
another_3 = np.arange(32, 36.1, (36-32)/2)

billboards = np.concatenate((first_3, another_3), axis=0)
print(billboards)

[17.  22.5 28.  32.  34.  36. ]


In [34]:
# Using linspace
first_3 = np.linspace(17, 28, 3)
another_3 = np.arange(32, 36, (36-32)/2)

billboards = np.concatenate((first_3, another_3), axis=0)
print(billboards)

[17.  22.5 28.  32.  34. ]


In [38]:
resturant_pos = 30

distances = np.abs(billboards[[1,4]] - resturant_pos)
print(distances)  # [7.5 4.]


[7.5 4. ]
